name: voyager
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.9.1
  - click=7.1.2
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - shapely=1.7.0
  - requests=2.24.0
  - requests_cache=0.4.13
  - geopy=2.0.0
  - pip:
    - click-log==0.3.2
    - git+https://github.com/philip-brohan/pyIMMA.git
